### ISSUE TITLE
Flexible configuration to scan a settings folder recursively

### ISSUE THREAD

**Issue by sergioa** [krakend/krakend-flexibleconfig#18]
We are using flexible configuration in such a way settings are grouped by different criteria such as API version, domain...

Ideally the flexible configuration should be able to scan a folder in a recursive manner.

```
root
│   settings_01.json    
│
└───folder1
│   │   settings_01.json
│   │   settings_02.json
│   │   ...
│   
└───folder2
    │   settings_01.json
    │   settings_02.json
```

Keys added to the map may include a prefix with a path relative to the root folder such as `folder1.settings_01` or `folder2.settings_01` to guarantee uniqueness.

**Comment by kpacha** [comment]
That's a great idea but I'm not sure about the proposed naming strategy... folder names, file names and properties could be mixed.

In order to demonstrate my point, picture this file structure:

```
.
├── a
│  ├── a
│  │  └── a.json
│  └── a.json
└── a.json
```
and, in order to take it even further, let's say this is the content of every `a.json` file

```
{
  "a":42
}
```

in hat scenario, what should be the result of this replacement:
```
{{.a.a}}
```
42, the content of the json file or the content of the directory `a/a`?


on the other hand, using the same standard used by filesystems (joining directories and file names with `/`) doesn't work with go templates. the parsing of `{{.a/a.a}}` fails with the error
```
bad character U+002F '/'
```
so I think we need another naming strategy

**Comment by sergioa** [comment]
Thanks @kpacha !

Indeed since `/` is not allowed, paths should be normalized. Maybe using `_` to concatenate folder names thus in your proposed scenario:

```
.
├── a
│  ├── a
│  │  └── a.json
│  └── a.json
└── a.json
```
```
{
  "a":42
}
```

we would end having:

`a_a_a.a`
`a_a.a`
`a.a`

Of course there may be edge scenarios if the user decides to include `_` in the folder name so `a/b_c/a.json` may collide with `a_b/c/a.json`.

**Comment by alombarte** [comment]
I think that if we choose to go for this functionality, the consistent approach with other existing KrakenD functionality would be to keep using the dot `.` whenever possible. 

Following your example:

```.
├── a
│  ├── a
│  │  └── a.json
│  └── a.json
└── a.json
```
If we speak about FC_SETTINGS for instance, my first thinking was that we could use the **dot** notation for all folder levels and the resolution of files could replace the `.` with `/` in the filesystem, and then append the extension of the desired file (.json). E.g:

- Notation `a.a.a` resolves to `a/a/a.json`
- Notation `a.a` resolves to `a/a.json`
- Notation `a` resolves to `a.json`

But the next problem is as you pointed out that the dot is also used to access the nested contents of the file:

```
cat a/a/a.json
{
    "b": {
        "b1": 42
    }
}
```

So the notation `a.a.a.b.b1` becomes completely impossible to calculate. In my opinion, I think this problem forces us to use a "context separator". Let's say we use `#` as the context separator. In the example above, this would be something like: 

```
a.a#a.b.b1    --> a/a/a.json, content b.b1
```

- Anyhting before the `#` is simply the suffix that we will append to the original `FC_SETTINGS` path.
- Everything after the `#` is the current notation of file and nesting level
- The abscense of the `#` separator makes everything work in the same way.

This approach still has the limitation that we cannot use dots in the folder names (e.g.: `settings/my.domain.com/production`) although we could either of:

a) check in the recursive scan of FC_content that there is no folder using this character, and if so `exit 1`.
b) document the naming limitation
c) Choose to use multiple `#` for each folder (e.g.: `a#a#a.b.b1`, but it's easier to explode having just one

It's a quick idea that maybe we can explore. And the `#` is no better than others, an example. I still need to think about it, but I wanted to leave the comment for you to digest.

**Comment by kpacha** [comment]
the `#` proposal doesn't work either:
```
bad character U+0023 '#'
```

**Comment by manuel-pancorbo** [comment]
hey @alombarte @kpacha! is there any news regarding this topic? We are really interested in it 😄

**Comment by alombarte** [comment]
Hi @manuel-pancorbo ,

Other than @sergioa no one has shown interest in this feature, so it's low priority. Please upvote the feature with a :+1:  reaction to the initial comment.

**Comment by alombarte** [comment]
The Enterprise edition introduces a new flexible configuration engine written from scratch (still, 100% compatible with the open-source edition and their go templates) that addresses this problem and many other limitations in the next version (EE 2.4). Therefore, we won't implement this functionality in the open-source edition.

Once we release EE 2.4 (~ August 2023), the documentation will be hosted in the URL https://www.krakend.io/docs/enterprise/configuration/flexible-config/, replacing the current content
