### ISSUE TITLE
recursive call

### ISSUE THREAD

**Issue by LiFeAiR** [krakend/krakend-flexibleconfig#6]
I have 4 files
a.json
```
{
 "b": {{ include "b.json" }}
}
```
b.json
```
{
 "c:" {{ include "c.json" }},
 "d": {{ include "d.json" }}
}
```
c.json
```
{
      "id": 1,
      "name": 1,
      "name1": 1
   }
```
d.json
```
{
      "id": 2,
      "name": 2,
      "name1": 2
   }
```
how about this case?

**Comment by kpacha** [comment]
Please, let me know if I am wrong but I guess `a.json` and `b.json` are templates and `c.json` and `d.json` are setting files, aren't they?

If that's the case, I'd define the `b.json` template like this:
```
{
 "c:" {{ marshall .c }},
 "d": {{ marshall .d }}
}
```

cheers!

**Comment by LiFeAiR** [comment]
No, all 4 files are templates
just the first 2 are top level templates
3 and 4 second level template files
it is quite possible that the third and fourth level of nesting will appear

**Comment by kpacha** [comment]
In order to parse several templates, I'd extend the `TemplateParser` struct and its constructor, so the `Parse` method could be able to scan a folder and add all the contained templates to the list of files to parse.

```
type TemplateParser struct {
    Vars      map[string]interface{}
    Partials  string
    Templates string
    Parser    config.Parser
    Path      string
    err       parserError
}

func (t *TemplateParser) Parse(configFile string) (config.ServiceConfig, error) {

    ...

    var buf bytes.Buffer

    templates := append([]string{configFile}, scanPartialTemplatesFolder(t.Templates)...)

    tmpl, err := t.newConfigTemplate().ParseFiles(templates...)

    ...
```
